---
name: 'test-submodule'

on:
  workflow_dispatch:

jobs:
  test-submodule:
    name: 'Test submodule'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - name: List jq submodule files
        run: |
          ls -la submodules/jq

      - name: List yq submodule files
        run: |
          ls -la submodules/yq
