---
name: 'test-submodule'

on:
  workflow_dispatch:

jobs:
  test-submodule:
    name: 'Test submodule'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: List submodule files
        run: |
          ls -la submodules
